### ISSUE TITLE
can't login if database is sqlite

### ISSUE THREAD

**Issue by hugozhu** [apicat/apicat#28]
type Users struct {
	ID        uint   `gorm:"type:**bigint**;primaryKey;autoIncrement"` 

sqlite field can be set as **autoIncrement** only if the type is integer and primary key

**Comment by hugozhu** [comment]
please also check: https://blog.csdn.net/qq1261275789/article/details/123606229

**Comment by gunnzhao** [comment]
> type Users struct { ID uint `gorm:"type:**bigint**;primaryKey;autoIncrement"`
> 
> sqlite field can be set as **autoIncrement** only if the type is integer and primary key

Thank you for your issue @hugozhu 

Our default database driver used to be SQLite, which worked fine for auto-incrementing primary keys. However, it failed to create tables on MySQL due to the difference in SQL syntax for auto-increment. As the majority of our users are using MySQL, we have decided to change the configuration to use MySQL instead and strongly recommend everyone to do the same.

If SQLite is your only option, you can refer to this [commit](https://github.com/apicat/apicat/commit/d072465dec185cd0810c9383192eba51ef56b553) of ours. However, I do not recommend doing so as there will be new data tables added in the future, and this is not a good solution.

**Comment by hugozhu** [comment]
sqlite is preferred for development and small team to use.  it's better to support mysql and sqlite.
